### ISSUE TITLE
Repeat rarefaction using a phyloseq object in R

### ISSUE THREAD

**Issue by shreyaskumbhare** [yxia0125/q2-repeat-rarefy#2]
Hi @yxia0125. I was wondering if you have a similar function in R that essentially gives out an averaged rarified table using a phyloseq object in R. I have used a couple of functions, but they have very different objective and hence a different output than what I am looking for. I am aware that the phyloseq object can be converted and imported in the qiime environment, however I am trying to avoid a lot of back and forth in my analysis pipeline. Any help is appreciated!
Thanks!

**Comment by xy-repo** [comment]
Hi @shreyaskumbhare, Sorry for the late response. I cannot find a similar function for phyloseq. Maybe it is easier to write a similar function with R. Just need to repeat rarefaction multiple times and calculate the average counts.

**Comment by shreyaskumbhare** [comment]
Thanks @yxia0125!
